### ISSUE TITLE
incorrectly detects "v := false" as a loop var

### ISSUE THREAD

**Issue by tmc** [karamaru-alpha/copyloopvar#10]
I believe there's an issue in loop var detection, take this example:

```go
	for i := range messages {
		// ...
		var text string
		foundText := false
```

gets reported as: `The copy of the 'for' variable "false" can be deleted (Go 1.22+) (copyloopvar)`

changing this to a `var foundText bool` silences the issue but I think this constitutes a bug.

**Comment by karamaru-alpha** [comment]
@tmc 
Thank you for your report!
I will fix it as soon as possible.
